export const ALPHA_THRESHOLD          = 10;    // 0–255
export const TEXT_SATURATION_MAX      = 0.15;  // 0–1  text is low-saturation
// Data vs label split is computed via connected-component height + Otsu's method in the worker
export const PREVIEW_SCALE_FACTOR     = 0.5;   // 50% downscale for preview
export const LARGE_IMAGE_MEGAPIXELS   = 20;    // show spinner above this

// Mask byte values
export const MASK_TRANSPARENT = 0;
export const MASK_MAP         = 1;
export const MASK_DATA        = 2;
export const MASK_LABEL       = 3;

export const PRESETS = [
  // Chromatic — ordered by hue (rainbow), Strava Orange pinned first
  { name: 'Strava Orange',     hue: 25,  sat: 1.0,  luminance: 0.5  },
  { name: 'Crimson Red',       hue: 0,   sat: 1.0,  luminance: 0.5  },
  { name: 'Sunset',            hue: 10,  sat: 1.0,  luminance: 0.5  },
  { name: 'Coral',             hue: 16,  sat: 1.0,  luminance: 0.66 },
  { name: 'Flame Orange',      hue: 19,  sat: 1.0,  luminance: 0.5  },
  { name: 'Persimmon',         hue: 27,  sat: 0.89, luminance: 0.47 },
  { name: 'Amber Glow',        hue: 38,  sat: 1.0,  luminance: 0.5  },
  { name: 'Saffron',           hue: 42,  sat: 1.0,  luminance: 0.59 },
  { name: 'Amber Gold',        hue: 45,  sat: 1.0,  luminance: 0.5  },
  { name: 'Gold',              hue: 51,  sat: 1.0,  luminance: 0.5  },
  { name: 'Bright Lemon',      hue: 56,  sat: 1.0,  luminance: 0.5  },
  { name: 'Canary Yellow',     hue: 60,  sat: 1.0,  luminance: 0.5  },
  { name: 'Lime Yellow',       hue: 68,  sat: 1.0,  luminance: 0.5  },
  { name: 'Chartreuse',        hue: 75,  sat: 1.0,  luminance: 0.5  },
  { name: 'Lawn Green',        hue: 90,  sat: 1.0,  luminance: 0.49 },
  { name: 'Sage',              hue: 92,  sat: 0.27, luminance: 0.49 },
  { name: 'Neon Green',        hue: 120, sat: 1.0,  luminance: 0.5  },
  { name: 'Kelly Green',       hue: 126, sat: 1.0,  luminance: 0.39 },
  { name: 'Forest',            hue: 140, sat: 0.8,  luminance: 0.5  },
  { name: 'Emerald',           hue: 145, sat: 0.63, luminance: 0.45 },
  { name: 'Evergreen',         hue: 158, sat: 0.96, luminance: 0.1  },
  { name: 'Tropical Mint',     hue: 165, sat: 1.0,  luminance: 0.5  },
  { name: 'Teal',              hue: 180, sat: 1.0,  luminance: 0.5  },
  { name: 'Ice Blue',          hue: 185, sat: 0.9,  luminance: 0.5  },
  { name: 'Cerulean',          hue: 195, sat: 1.0,  luminance: 0.5  },
  { name: 'Oxford Navy',       hue: 209, sat: 1.0,  luminance: 0.19 },
  { name: 'Ocean',             hue: 220, sat: 1.0,  luminance: 0.5  },
  { name: 'Twilight Indigo',   hue: 224, sat: 0.5,  luminance: 0.25 },
  { name: 'Electric Sapphire', hue: 230, sat: 1.0,  luminance: 0.64 },
  { name: 'Periwinkle',        hue: 236, sat: 0.67, luminance: 0.74 },
  { name: 'Navy Electric',     hue: 240, sat: 1.0,  luminance: 0.31 },
  { name: 'Royal Purple',      hue: 267, sat: 1.0,  luminance: 0.41 },
  { name: 'Magenta',           hue: 300, sat: 1.0,  luminance: 0.5  },
  { name: 'Orchid',            hue: 302, sat: 0.59, luminance: 0.65 },
  { name: 'Vapor Wave',        hue: 310, sat: 0.9,  luminance: 0.5  },
  { name: 'Neon Pink',         hue: 330, sat: 1.0,  luminance: 0.5  },
  { name: 'Rose',              hue: 338, sat: 0.76, luminance: 0.62 },
  { name: 'Hot Fuchsia',       hue: 341, sat: 1.0,  luminance: 0.5  },
  { name: 'Dark Amaranth',     hue: 343, sat: 0.69, luminance: 0.29 },
  { name: 'Deep Crimson',      hue: 350, sat: 1.0,  luminance: 0.29 },
  
  // Neutrals — dark → light
  { name: 'Black',             hue: 0,   sat: 0.0,  luminance: 0.0  },
  { name: 'Jet Black',         hue: 200, sat: 0.15, luminance: 0.19 },
  { name: 'Slate',             hue: 210, sat: 0.13, luminance: 0.25 },
  { name: 'Charcoal',          hue: 0,   sat: 0.0,  luminance: 0.33 },
  { name: 'Dim Grey',          hue: 0,   sat: 0.0,  luminance: 0.41 },
  { name: 'Grey',              hue: 0,   sat: 0.0,  luminance: 0.5  },
  { name: 'Monochrome',        hue: 0,   sat: 0.0,  luminance: 0.5  },
  { name: 'Silver',            hue: 0,   sat: 0.0,  luminance: 0.75 },
  { name: 'Alabaster',         hue: 40,  sat: 0.05, luminance: 0.89 },
  { name: 'White',             hue: 0,   sat: 0.0,  luminance: 1.0  },
];

export const DEFAULT_MAP_PRESET   = PRESETS.findIndex(p => p.name === 'Strava Orange');
export const DEFAULT_DATA_PRESET  = PRESETS.findIndex(p => p.name === 'White');
export const DEFAULT_LABEL_PRESET = PRESETS.findIndex(p => p.name === 'White');

export const COLORWAYS = [
  // ── Auto-generated from single-layer color presets (same color on all layers)
  ...PRESETS.map(p => ({
    name:  p.name,
    group: 'Mono',
    map:   { hue: p.hue, sat: p.sat, luminance: p.luminance },
    data:  { hue: p.hue, sat: p.sat, luminance: p.luminance },
    label: { hue: p.hue, sat: p.sat, luminance: p.luminance },
  })),
  // ── Colorways from colorway.html ─────────────────────────────────────────
  {
    name:  "Adidas Aurora Metallic",
    group: 'Running',
    data:  { hue: 87, sat: 0.1, luminance: 0.65 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 1.0, luminance: 0.50 },
  },
  {
    name:  "Adidas Lucid Lemon",
    group: 'Running',
    data:  { hue: 65, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 338, sat: 0.8, luminance: 0.79 },
  },
  {
    name:  "Adidas Non-Dyed Strata",
    group: 'Running',
    data:  { hue: 60, sat: 0.6, luminance: 0.91 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 30, sat: 0.2, luminance: 0.36 },
  },
  {
    name:  "Adidas Pulse Mint",
    group: 'Running',
    data:  { hue: 120, sat: 1.0, luminance: 0.80 },
    map:   { hue: 300, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Adidas Signal Coral",
    group: 'Running',
    data:  { hue: 16, sat: 1.0, luminance: 0.66 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Adidas Solar Yellow",
    group: 'Running',
    data:  { hue: 60, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Asics Cherry Tomato",
    group: 'Running',
    data:  { hue: 5, sat: 0.9, luminance: 0.56 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Asics Digital Aqua Marigold",
    group: 'Running',
    data:  { hue: 195, sat: 1.0, luminance: 0.50 },
    map:   { hue: 40, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Asics Glow Yellow",
    group: 'Running',
    data:  { hue: 68, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Asics Hazard Green & Sky",
    group: 'Running',
    data:  { hue: 67, sat: 1.0, luminance: 0.50 },
    map:   { hue: 197, sat: 0.7, luminance: 0.73 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Asics Island Blue Orange Pop",
    group: 'Running',
    data:  { hue: 210, sat: 1.0, luminance: 0.40 },
    map:   { hue: 25, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Asics Sunrise Speed",
    group: 'Running',
    data:  { hue: 4, sat: 1.0, luminance: 0.62 },
    map:   { hue: 213, sat: 1.0, luminance: 0.18 },
    label: { hue: 0, sat: 0.0, luminance: 0.85 },
  },
  {
    name:  "Brooks Coral & Black",
    group: 'Running',
    data:  { hue: 16, sat: 1.0, luminance: 0.66 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Brooks Hyper Blue & Yellow",
    group: 'Running',
    data:  { hue: 220, sat: 1.0, luminance: 0.50 },
    map:   { hue: 51, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Brooks Nightlife",
    group: 'Running',
    data:  { hue: 67, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 207, sat: 0.1, luminance: 0.61 },
  },
  {
    name:  "Brooks Peacoat Atomic Blue",
    group: 'Running',
    data:  { hue: 218, sat: 0.4, luminance: 0.13 },
    map:   { hue: 197, sat: 1.0, luminance: 0.45 },
    label: { hue: 330, sat: 1.0, luminance: 0.50 },
  },
  {
    name:  "Hoka Butterfly",
    group: 'Running',
    data:  { hue: 330, sat: 1.0, luminance: 0.71 },
    map:   { hue: 203, sat: 0.9, luminance: 0.75 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Hoka Fiesta",
    group: 'Running',
    data:  { hue: 0, sat: 1.0, luminance: 0.63 },
    map:   { hue: 30, sat: 1.0, luminance: 0.60 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Hoka Goblin Blue",
    group: 'Running',
    data:  { hue: 197, sat: 0.7, luminance: 0.73 },
    map:   { hue: 157, sat: 1.0, luminance: 0.49 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Hoka Impala",
    group: 'Running',
    data:  { hue: 51, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Hoka Lava Orange",
    group: 'Running',
    map:   { hue: 0,   sat: 0.0, luminance: 1.0 },
    data:  { hue: 22,  sat: 0.9, luminance: 0.5 },
    label: { hue: 280, sat: 0.7, luminance: 0.5 },
  },
  {
    name:  "Hoka Ocean & Sun",
    group: 'Running',
    data:  { hue: 187, sat: 0.3, luminance: 0.40 },
    map:   { hue: 50, sat: 0.9, luminance: 0.63 },
    label: { hue: 35, sat: 0.4, luminance: 0.75 },
  },
  {
    name:  "Hoka Scuba Blue",
    group: 'Running',
    data:  { hue: 195, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "NB Arctic Fox",
    group: 'Running',
    data:  { hue: 201, sat: 0.6, luminance: 0.85 },
    map:   { hue: 255, sat: 0.0, luminance: 0.67 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "NB Bleach Blue",
    group: 'Running',
    data:  { hue: 195, sat: 0.5, luminance: 0.79 },
    map:   { hue: 328, sat: 1.0, luminance: 0.54 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "NB Cosmic Pineapple",
    group: 'Running',
    data:  { hue: 51, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "NB Cyber Jade",
    group: 'Running',
    data:  { hue: 150, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "NB Eclipse Sky",
    group: 'Running',
    data:  { hue: 236, sat: 0.2, luminance: 0.14 },
    map:   { hue: 50, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "NB Energy Lime",
    group: 'Running',
    data:  { hue: 72, sat: 1.0, luminance: 0.50 },
    map:   { hue: 285, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "NB Lava Flare",
    group: 'Running',
    data:  { hue: 355, sat: 0.8, luminance: 0.56 },
    map:   { hue: 204, sat: 0.2, luminance: 0.26 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "NB Neon Dragonfly",
    group: 'Running',
    data:  { hue: 180, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "NB Pixel Green",
    group: 'Running',
    data:  { hue: 120, sat: 0.6, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "NB Vibrant Apricot",
    group: 'Running',
    data:  { hue: 24, sat: 0.9, luminance: 0.84 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Nike Barely Volt",
    group: 'Running',
    data:  { hue: 68, sat: 1.0, luminance: 0.50 },
    map:   { hue: 181, sat: 1.0, luminance: 0.41 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Nike Bright Mango",
    group: 'Running',
    data:  { hue: 20, sat: 1.0, luminance: 0.63 },
    map:   { hue: 0, sat: 0.0, luminance: 0.75 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Nike Ekiden Zoom",
    group: 'Running',
    data:  { hue: 150, sat: 1.0, luminance: 0.50 },
    map:   { hue: 54, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Nike Hakone",
    group: 'Running',
    data:  { hue: 158, sat: 1.0, luminance: 0.33 },
    map:   { hue: 55, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Nike Hyper Turquoise",
    group: 'Running',
    data:  { hue: 181, sat: 1.0, luminance: 0.41 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Nike Kipchoge 159",
    group: 'Running',
    data:  { hue: 330, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Nike Mint Foam",
    group: 'Running',
    data:  { hue: 120, sat: 1.0, luminance: 0.80 },
    map:   { hue: 72, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 0.20 },
  },
  {
    name:  "Nike Proto",
    group: 'Running',
    data:  { hue: 21, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Nike Raw Kinetic",
    group: 'Running',
    data:  { hue: 40, sat: 0.1, luminance: 0.89 },
    map:   { hue: 226, sat: 0.5, luminance: 0.58 },
    label: { hue: 348, sat: 0.8, luminance: 0.47 },
  },
  {
    name:  "Nike Volt & Stealth",
    group: 'Running',
    data:  { hue: 72, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.07 },
    label: { hue: 0, sat: 0.0, luminance: 0.90 },
  },
  {
    name:  "Nike Watermelon",
    group: 'Running',
    data:  { hue: 330, sat: 1.0, luminance: 0.50 },
    map:   { hue: 120, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "ON Alloy & Tide",
    group: 'Running',
    data:  { hue: 207, sat: 0.1, luminance: 0.61 },
    map:   { hue: 180, sat: 1.0, luminance: 0.27 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "ON Flame & Shadow",
    group: 'Running',
    data:  { hue: 16, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.20 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "ON Glacier & Eclipse",
    group: 'Running',
    data:  { hue: 192, sat: 0.1, luminance: 0.84 },
    map:   { hue: 222, sat: 0.2, luminance: 0.14 },
    label: { hue: 12, sat: 1.0, luminance: 0.61 },
  },
  {
    name:  "ON Mint & Surf",
    group: 'Running',
    data:  { hue: 120, sat: 1.0, luminance: 0.80 },
    map:   { hue: 181, sat: 1.0, luminance: 0.41 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "ON Mustard & Rock",
    group: 'Running',
    data:  { hue: 47, sat: 1.0, luminance: 0.67 },
    map:   { hue: 0, sat: 0.0, luminance: 0.29 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Puma Elektro Peach",
    group: 'Running',
    data:  { hue: 28, sat: 1.0, luminance: 0.86 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Puma Fireglow",
    group: 'Running',
    data:  { hue: 16, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Puma Fizzy Light",
    group: 'Running',
    data:  { hue: 180, sat: 1.0, luminance: 0.94 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Puma Lime Squeeze",
    group: 'Running',
    data:  { hue: 72, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 40, sat: 0.1, luminance: 0.89 },
  },
  {
    name:  "Puma Psychedelic Rush",
    group: 'Running',
    data:  { hue: 266, sat: 1.0, luminance: 0.26 },
    map:   { hue: 66, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Puma Royal Sapphire",
    group: 'Running',
    data:  { hue: 205, sat: 1.0, luminance: 0.31 },
    map:   { hue: 12, sat: 1.0, luminance: 0.67 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Puma Sunset Glow",
    group: 'Running',
    data:  { hue: 17, sat: 1.0, luminance: 0.74 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Salomon Lunar Rock",
    group: 'Running',
    data:  { hue: 0, sat: 0.0, luminance: 0.75 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Salomon Magnet",
    group: 'Running',
    data:  { hue: 200, sat: 0.2, luminance: 0.39 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Salomon Racing Red",
    group: 'Running',
    data:  { hue: 0, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Saucony Campfire",
    group: 'Running',
    data:  { hue: 33, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Saucony Future Neon",
    group: 'Running',
    data:  { hue: 110, sat: 1.0, luminance: 0.54 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Saucony Mutant",
    group: 'Running',
    data:  { hue: 90, sat: 1.0, luminance: 0.50 },
    map:   { hue: 300, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Saucony Quartz",
    group: 'Running',
    data:  { hue: 350, sat: 1.0, luminance: 0.88 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Saucony Reverie",
    group: 'Running',
    data:  { hue: 225, sat: 0.7, luminance: 0.57 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Saucony Slime",
    group: 'Running',
    data:  { hue: 75, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Saucony ViziOrange",
    group: 'Running',
    data:  { hue: 20, sat: 1.0, luminance: 0.50 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 265, sat: 0.3, luminance: 0.25 },
  },
  {
    name:  "Saucony ViziPro",
    group: 'Running',
    data:  { hue: 16, sat: 1.0, luminance: 0.50 },
    map:   { hue: 60, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Saucony ViziRed",
    group: 'Running',
    data:  { hue: 0, sat: 0.0, luminance: 0.00 },
    map:   { hue: 347, sat: 1.0, luminance: 0.50 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Asics Cobalt Burst Orange",
    group: 'Running',
    data:  { hue: 210, sat: 1.0, luminance: 0.40 },
    map:   { hue: 25, sat: 1.0, luminance: 0.50 },
    label: { hue: 150, sat: 1.0, luminance: 0.50 },
  },
  {
    name:  "Asics Ekiden Race",
    group: 'Running',
    data:  { hue: 141, sat: 0.49, luminance: 0.59 },
    map:   { hue: 96,  sat: 0.77, luminance: 0.73 },
    label: { hue: 140, sat: 0.32, luminance: 0.15 },
  },
  {
    name:  "Saucony London Crimson",
    group: 'Running',
    data:  { hue: 360, sat: 0.80, luminance: 0.32 },
    map:   { hue: 358, sat: 0.78, luminance: 0.22 },
    label: { hue: 226, sat: 0.26, luminance: 0.27 },
  },
  {
    name:  "Saucony Mutant Beast",
    group: 'Running',
    data:  { hue: 340, sat: 0.98, luminance: 0.59 },
    map:   { hue: 78,  sat: 1.0,  luminance: 0.52 },
    label: { hue: 175, sat: 0.92, luminance: 0.50 },
  },
  {
    name:  "Saucony Mutant Cyclops",
    group: 'Running',
    data:  { hue: 0,   sat: 0.0,  luminance: 0.92 },
    map:   { hue: 340, sat: 0.98, luminance: 0.59 },
    label: { hue: 182, sat: 0.60, luminance: 0.45 },
  },
  {
    name:  "Saucony Mutant Domino",
    group: 'Running',
    data:  { hue: 0,   sat: 0.0,  luminance: 0.96 },
    map:   { hue: 70,  sat: 1.0,  luminance: 0.50 },
    label: { hue: 180, sat: 0.55, luminance: 0.50 },
  },
  {
    name:  "Saucony Mutant Enigma",
    group: 'Running',
    data:  { hue: 78,  sat: 1.0,  luminance: 0.52 },
    map:   { hue: 340, sat: 0.98, luminance: 0.59 },
    label: { hue: 220, sat: 0.20, luminance: 0.15 },
  },
  // ── Mechanical Keyboard Keycap colorways ──────────────────────────────────
  {
    name:  "9009",
    group: 'MechKeeb',
    data:  { hue: 43, sat: 0.21, luminance: 0.81 },
    map:   { hue: 46, sat: 0.13, luminance: 0.63 },
    label: { hue: 122, sat: 0.17, luminance: 0.57 },
  },
  {
    name:  "Belafonte",
    group: 'MechKeeb',
    data:  { hue: 182, sat: 1.0, luminance: 0.33 },
    map:   { hue: 42, sat: 1.0, luminance: 0.45 },
    label: { hue: 37, sat: 0.45, luminance: 0.94 },
  },
  {
    name:  "Bento",
    group: 'MechKeeb',
    data:  { hue: 37, sat: 0.45, luminance: 0.94 },
    map:   { hue: 214, sat: 0.52, luminance: 0.25 },
    label: { hue: 339, sat: 0.58, luminance: 0.52 },
  },
  {
    name:  "Bleached",
    group: 'MechKeeb',
    data:  { hue: 0, sat: 0.0, luminance: 1.00 },
    map:   { hue: 38, sat: 0.21, luminance: 0.85 },
    label: { hue: 216, sat: 0.05, luminance: 0.78 },
  },
  {
    name:  "Blue Samurai",
    group: 'MechKeeb',
    data:  { hue: 207, sat: 1.0, luminance: 0.31 },
    map:   { hue: 180, sat: 0.02, luminance: 0.23 },
    label: { hue: 47, sat: 1.0, luminance: 0.49 },
  },
  {
    name:  "BoW",
    group: 'MechKeeb',
    data:  { hue: 37, sat: 0.45, luminance: 0.94 },
    map:   { hue: 240, sat: 0.02, luminance: 0.09 },
    label: { hue: 216, sat: 0.05, luminance: 0.78 },
  },
  {
    name:  "Botanical",
    group: 'MechKeeb',
    data:  { hue: 36, sat: 0.47, luminance: 0.87 },
    map:   { hue: 149, sat: 1.0, luminance: 0.23 },
    label: { hue: 90, sat: 0.50, luminance: 0.41 },
  },
  {
    name:  "Camping",
    group: 'MechKeeb',
    data:  { hue: 38, sat: 0.21, luminance: 0.85 },
    map:   { hue: 111, sat: 0.11, luminance: 0.50 },
    label: { hue: 354, sat: 0.86, luminance: 0.47 },
  },
  {
    name:  "Classic Retro",
    group: 'MechKeeb',
    data:  { hue: 36, sat: 0.47, luminance: 0.87 },
    map:   { hue: 60, sat: 0.07, luminance: 0.75 },
    label: { hue: 354, sat: 0.59, luminance: 0.35 },
  },
  {
    name:  "Dolch",
    group: 'MechKeeb',
    data:  { hue: 180, sat: 0.01, luminance: 0.45 },
    map:   { hue: 216, sat: 0.05, luminance: 0.78 },
    label: { hue: 6, sat: 0.76, luminance: 0.46 },
  },
  {
    name:  "Dracula",
    group: 'MechKeeb',
    data:  { hue: 231, sat: 0.15, luminance: 0.18 },
    map:   { hue: 265, sat: 0.89, luminance: 0.78 },
    label: { hue: 135, sat: 0.94, luminance: 0.65 },
  },
  {
    name:  "Godspeed",
    group: 'MechKeeb',
    data:  { hue: 36, sat: 0.47, luminance: 0.87 },
    map:   { hue: 199, sat: 1.0, luminance: 0.38 },
    label: { hue: 6, sat: 0.76, luminance: 0.46 },
  },
  {
    name:  "Hennessey",
    group: 'MechKeeb',
    data:  { hue: 37, sat: 0.45, luminance: 0.94 },
    map:   { hue: 216, sat: 0.05, luminance: 0.78 },
    label: { hue: 180, sat: 0.02, luminance: 0.23 },
  },
  {
    name:  "Honeywell",
    group: 'MechKeeb',
    data:  { hue: 37, sat: 0.45, luminance: 0.94 },
    map:   { hue: 216, sat: 0.05, luminance: 0.78 },
    label: { hue: 6, sat: 0.76, luminance: 0.46 },
  },
  {
    name:  "Hydro",
    group: 'MechKeeb',
    data:  { hue: 192, sat: 1.0, luminance: 0.24 },
    map:   { hue: 207, sat: 1.0, luminance: 0.31 },
    label: { hue: 54, sat: 1.0, luminance: 0.46 },
  },
  {
    name:  "Hyperfuse",
    group: 'MechKeeb',
    data:  { hue: 216, sat: 0.05, luminance: 0.78 },
    map:   { hue: 266, sat: 0.31, luminance: 0.38 },
    label: { hue: 182, sat: 1.0, luminance: 0.33 },
  },
  {
    name:  "Kaiju",
    group: 'MechKeeb',
    data:  { hue: 141, sat: 0.30, luminance: 0.32 },
    map:   { hue: 26, sat: 1.0, luminance: 0.47 },
    label: { hue: 37, sat: 0.45, luminance: 0.94 },
  },
  {
    name:  "Laser",
    group: 'MechKeeb',
    data:  { hue: 259, sat: 0.49, luminance: 0.21 },
    map:   { hue: 333, sat: 1.0, luminance: 0.59 },
    label: { hue: 192, sat: 1.0, luminance: 0.50 },
  },
  {
    name:  "Nautilus",
    group: 'MechKeeb',
    data:  { hue: 210, sat: 0.69, luminance: 0.18 },
    map:   { hue: 47, sat: 1.0, luminance: 0.49 },
    label: { hue: 37, sat: 0.45, luminance: 0.94 },
  },
  {
    name:  "Olivia",
    group: 'MechKeeb',
    data:  { hue: 37, sat: 0.45, luminance: 0.94 },
    map:   { hue: 240, sat: 0.02, luminance: 0.09 },
    label: { hue: 339, sat: 0.58, luminance: 0.52 },
  },
  {
    name:  "Penumbra",
    group: 'MechKeeb',
    data:  { hue: 180, sat: 0.02, luminance: 0.23 },
    map:   { hue: 40, sat: 0.06, luminance: 0.38 },
    label: { hue: 54, sat: 1.0, luminance: 0.46 },
  },
  {
    name:  "Red Samurai",
    group: 'MechKeeb',
    data:  { hue: 3, sat: 0.72, luminance: 0.43 },
    map:   { hue: 180, sat: 0.02, luminance: 0.23 },
    label: { hue: 54, sat: 1.0, luminance: 0.46 },
  },
  {
    name:  "Serika",
    group: 'MechKeeb',
    data:  { hue: 37, sat: 0.45, luminance: 0.94 },
    map:   { hue: 54, sat: 1.0, luminance: 0.46 },
    label: { hue: 26, sat: 1.0, luminance: 0.47 },
  },
  {
    name:  "Wavez",
    group: 'MechKeeb',
    data:  { hue: 170, sat: 0.25, luminance: 0.14 },
    map:   { hue: 111, sat: 1.0, luminance: 0.54 },
    label: { hue: 240, sat: 0.02, luminance: 0.09 },
  },
  {
    name:  "WoB",
    group: 'MechKeeb',
    data:  { hue: 240, sat: 0.02, luminance: 0.09 },
    map:   { hue: 37, sat: 0.45, luminance: 0.94 },
    label: { hue: 180, sat: 0.02, luminance: 0.23 },
  },  // ── EPL Club colorways ────────────────────────────────────────────────────
  {
    name:  "Arsenal",
    group: 'EPL',
    data:  { hue: 358, sat: 0.99, luminance: 0.47 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 213, sat: 0.90, luminance: 0.24 },
  },
  {
    name:  "Aston Villa",
    group: 'EPL',
    data:  { hue: 333, sat: 0.76, luminance: 0.23 },
    map:   { hue: 208, sat: 0.61, luminance: 0.74 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Bournemouth",
    group: 'EPL',
    data:  { hue: 4, sat: 0.77, luminance: 0.48 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Brentford",
    group: 'EPL',
    data:  { hue: 356, sat: 0.95, luminance: 0.46 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 44, sat: 1.0, luminance: 0.49 },
  },
  {
    name:  "Brighton",
    group: 'EPL',
    data:  { hue: 212, sat: 1.0, luminance: 0.36 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 48, sat: 1.0, luminance: 0.50 },
  },
  {
    name:  "Burnley",
    group: 'EPL',
    data:  { hue: 330, sat: 0.58, luminance: 0.27 },
    map:   { hue: 195, sat: 0.66, luminance: 0.76 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Chelsea",
    group: 'EPL',
    data:  { hue: 212, sat: 0.96, luminance: 0.30 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 43, sat: 0.86, luminance: 0.46 },
  },
  {
    name:  "Crystal Palace",
    group: 'EPL',
    data:  { hue: 218, sat: 0.68, luminance: 0.33 },
    map:   { hue: 351, sat: 0.83, luminance: 0.42 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Everton",
    group: 'EPL',
    data:  { hue: 220, sat: 1.0, luminance: 0.30 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Fulham",
    group: 'EPL',
    data:  { hue: 0, sat: 0.0, luminance: 1.00 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 1.0, luminance: 0.40 },
  },
  {
    name:  "Leeds United",
    group: 'EPL',
    data:  { hue: 0, sat: 0.0, luminance: 1.00 },
    map:   { hue: 220, sat: 0.65, luminance: 0.33 },
    label: { hue: 48, sat: 1.0, luminance: 0.50 },
  },
  {
    name:  "Liverpool",
    group: 'EPL',
    data:  { hue: 350, sat: 0.85, luminance: 0.42 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 177, sat: 1.0, luminance: 0.35 },
  },
  {
    name:  "Manchester City",
    group: 'EPL',
    data:  { hue: 207, sat: 0.62, luminance: 0.65 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 225, sat: 0.53, luminance: 0.23 },
  },
  {
    name:  "Manchester Utd",
    group: 'EPL',
    data:  { hue: 4, sat: 0.77, luminance: 0.48 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Newcastle Utd",
    group: 'EPL',
    data:  { hue: 348, sat: 0.07, luminance: 0.13 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 195, sat: 1.0, luminance: 0.47 },
  },
  {
    name:  "Nott'm Forest",
    group: 'EPL',
    data:  { hue: 0, sat: 1.0, luminance: 0.43 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Sunderland",
    group: 'EPL',
    data:  { hue: 354, sat: 0.84, luminance: 0.51 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Tottenham",
    group: 'EPL',
    data:  { hue: 0, sat: 0.0, luminance: 1.00 },
    map:   { hue: 227, sat: 0.64, luminance: 0.21 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "West Ham Utd",
    group: 'EPL',
    data:  { hue: 346, sat: 0.53, luminance: 0.31 },
    map:   { hue: 196, sat: 0.81, luminance: 0.51 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Wolves",
    group: 'EPL',
    data:  { hue: 43, sat: 0.98, luminance: 0.53 },
    map:   { hue: 345, sat: 0.06, luminance: 0.13 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  // ── NBA Team colorways ────────────────────────────────────────────────────
  {
    name:  "76ers",
    group: 'NBA',
    data:  { hue: 205, sat: 1.0, luminance: 0.36 },
    map:   { hue: 345, sat: 0.86, luminance: 0.51 },
    label: { hue: 212, sat: 1.0, luminance: 0.18 },
  },
  {
    name:  "Bucks",
    group: 'NBA',
    data:  { hue: 143, sat: 1.0, luminance: 0.14 },
    map:   { hue: 40, sat: 0.54, luminance: 0.85 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Bulls",
    group: 'NBA',
    data:  { hue: 345, sat: 0.85, luminance: 0.44 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Cavaliers",
    group: 'NBA',
    data:  { hue: 335, sat: 1.0, luminance: 0.26 },
    map:   { hue: 41, sat: 0.98, luminance: 0.59 },
    label: { hue: 215, sat: 0.89, luminance: 0.14 },
  },
  {
    name:  "Celtics",
    group: 'NBA',
    data:  { hue: 145, sat: 1.0, luminance: 0.24 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 39, sat: 0.43, luminance: 0.53 },
  },
  {
    name:  "Clippers",
    group: 'NBA',
    data:  { hue: 350, sat: 0.85, luminance: 0.42 },
    map:   { hue: 220, sat: 0.65, luminance: 0.33 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Grizzlies",
    group: 'NBA',
    data:  { hue: 220, sat: 0.31, luminance: 0.51 },
    map:   { hue: 233, sat: 0.56, luminance: 0.16 },
    label: { hue: 42, sat: 0.92, luminance: 0.52 },
  },
  {
    name:  "Hawks",
    group: 'NBA',
    data:  { hue: 359, sat: 0.73, luminance: 0.55 },
    map:   { hue: 67, sat: 0.65, luminance: 0.51 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Heat",
    group: 'NBA',
    data:  { hue: 342, sat: 1.0, luminance: 0.30 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 36, sat: 0.95, luminance: 0.54 },
  },
  {
    name:  "Hornets",
    group: 'NBA',
    data:  { hue: 249, sat: 0.70, luminance: 0.22 },
    map:   { hue: 189, sat: 1.0, luminance: 0.27 },
    label: { hue: 240, sat: 0.02, luminance: 0.64 },
  },
  {
    name:  "Jazz",
    group: 'NBA',
    data:  { hue: 212, sat: 1.0, luminance: 0.18 },
    map:   { hue: 36, sat: 0.95, luminance: 0.54 },
    label: { hue: 143, sat: 1.0, luminance: 0.14 },
  },
  {
    name:  "Kings",
    group: 'NBA',
    data:  { hue: 272, sat: 0.48, luminance: 0.34 },
    map:   { hue: 201, sat: 0.10, luminance: 0.43 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Knicks",
    group: 'NBA',
    data:  { hue: 205, sat: 1.0, luminance: 0.36 },
    map:   { hue: 27, sat: 0.91, luminance: 0.55 },
    label: { hue: 210, sat: 0.03, luminance: 0.75 },
  },
  {
    name:  "Lakers",
    group: 'NBA',
    data:  { hue: 271, sat: 0.56, luminance: 0.33 },
    map:   { hue: 41, sat: 0.98, luminance: 0.57 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Magic",
    group: 'NBA',
    data:  { hue: 203, sat: 1.0, luminance: 0.38 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 203, sat: 0.16, luminance: 0.80 },
  },
  {
    name:  "Mavericks",
    group: 'NBA',
    data:  { hue: 204, sat: 1.0, luminance: 0.27 },
    map:   { hue: 213, sat: 1.0, luminance: 0.18 },
    label: { hue: 200, sat: 0.15, luminance: 0.76 },
  },
  {
    name:  "Nets",
    group: 'NBA',
    data:  { hue: 0, sat: 0.0, luminance: 0.00 },
    map:   { hue: 0, sat: 0.0, luminance: 1.00 },
    label: { hue: 203, sat: 0.16, luminance: 0.80 },
  },
  {
    name:  "Nuggets",
    group: 'NBA',
    data:  { hue: 216, sat: 0.64, luminance: 0.15 },
    map:   { hue: 44, sat: 0.99, luminance: 0.57 },
    label: { hue: 351, sat: 0.62, luminance: 0.34 },
  },
  {
    name:  "Pacers",
    group: 'NBA',
    data:  { hue: 212, sat: 1.0, luminance: 0.19 },
    map:   { hue: 41, sat: 0.98, luminance: 0.59 },
    label: { hue: 210, sat: 0.03, luminance: 0.75 },
  },
  {
    name:  "Pelicans",
    group: 'NBA',
    data:  { hue: 213, sat: 0.68, luminance: 0.15 },
    map:   { hue: 350, sat: 0.85, luminance: 0.42 },
    label: { hue: 39, sat: 0.27, luminance: 0.41 },
  },
  {
    name:  "Pistons",
    group: 'NBA',
    data:  { hue: 350, sat: 0.85, luminance: 0.42 },
    map:   { hue: 226, sat: 0.73, luminance: 0.42 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Raptors",
    group: 'NBA',
    data:  { hue: 345, sat: 0.85, luminance: 0.44 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 240, sat: 0.02, luminance: 0.64 },
  },
  {
    name:  "Rockets",
    group: 'NBA',
    data:  { hue: 345, sat: 0.85, luminance: 0.44 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 203, sat: 0.16, luminance: 0.80 },
  },
  {
    name:  "Spurs",
    group: 'NBA',
    data:  { hue: 0, sat: 0.0, luminance: 0.00 },
    map:   { hue: 203, sat: 0.16, luminance: 0.80 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Suns",
    group: 'NBA',
    data:  { hue: 249, sat: 0.70, luminance: 0.22 },
    map:   { hue: 19, sat: 0.79, luminance: 0.51 },
    label: { hue: 0, sat: 0.0, luminance: 0.00 },
  },
  {
    name:  "Thunder",
    group: 'NBA',
    data:  { hue: 202, sat: 1.0, luminance: 0.38 },
    map:   { hue: 24, sat: 1.0, luminance: 0.47 },
    label: { hue: 41, sat: 0.98, luminance: 0.59 },
  },
  {
    name:  "Timberwolves",
    group: 'NBA',
    data:  { hue: 213, sat: 0.68, luminance: 0.15 },
    map:   { hue: 206, sat: 0.61, luminance: 0.35 },
    label: { hue: 87, sat: 0.71, luminance: 0.44 },
  },
  {
    name:  "Trail Blazers",
    group: 'NBA',
    data:  { hue: 359, sat: 0.73, luminance: 0.55 },
    map:   { hue: 0, sat: 0.0, luminance: 0.00 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Warriors",
    group: 'NBA',
    data:  { hue: 220, sat: 0.65, luminance: 0.33 },
    map:   { hue: 44, sat: 1.0, luminance: 0.59 },
    label: { hue: 0, sat: 0.0, luminance: 1.00 },
  },
  {
    name:  "Wizards",
    group: 'NBA',
    data:  { hue: 212, sat: 1.0, luminance: 0.18 },
    map:   { hue: 351, sat: 0.81, luminance: 0.49 },
    label: { hue: 203, sat: 0.16, luminance: 0.80 },
  },
  // ── Liga Super Indonesia (ISL) colorways ────────────────────────────────────
  {
    name:  "Arema FC (Malang)",
    group: 'ISL',
    data:  { hue: 217, sat: 1, luminance: 0.27 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 351, sat: 0.85, luminance: 0.44 },
  },
  {
    name:  "Bali United FC (Gianyar)",
    group: 'ISL',
    data:  { hue: 355, sat: 0.96, luminance: 0.53 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 0, sat: 0, luminance: 0.12 },
  },
  {
    name:  "Barito Putera (Banjarbaru)",
    group: 'ISL',
    data:  { hue: 154, sat: 1, luminance: 0.32 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  {
    name:  "Bhayangkara Presisi FC (Jakarta)",
    group: 'ISL',
    data:  { hue: 210, sat: 1, luminance: 0.19 },
    map:   { hue: 48, sat: 1, luminance: 0.5 },
    label: { hue: 0, sat: 0, luminance: 0.12 },
  },
  {
    name:  "Borneo FC Samarinda (Samarinda)",
    group: 'ISL',
    data:  { hue: 154, sat: 1, luminance: 0.32 },
    map:   { hue: 45, sat: 0.95, luminance: 0.55 },
    label: { hue: 0, sat: 0, luminance: 0.12 },
  },
  {
    name:  "Dewa United FC (Tangerang)",
    group: 'ISL',
    data:  { hue: 265, sat: 0.53, luminance: 0.37 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 45, sat: 0.92, luminance: 0.65 },
  },
  {
    name:  "Madura United FC (Pamekasan)",
    group: 'ISL',
    data:  { hue: 210, sat: 1, luminance: 0.19 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 27, sat: 1, luminance: 0.5 },
  },
  {
    name:  "Malut United (Ternate)",
    group: 'ISL',
    data:  { hue: 48, sat: 1, luminance: 0.5 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 351, sat: 0.85, luminance: 0.44 },
  },
  {
    name:  "Persebaya Surabaya (Surabaya)",
    group: 'ISL',
    data:  { hue: 154, sat: 1, luminance: 0.27 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 0, sat: 0, luminance: 0.12 },
  },
  {
    name:  "Persib Bandung",
    group: 'ISL',
    data:  { hue: 217, sat: 1, luminance: 0.31 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 48, sat: 1, luminance: 0.5 },
  },
  {
    name:  "Persija Jakarta",
    group: 'ISL',
    data:  { hue: 27, sat: 1, luminance: 0.5 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  {
    name:  "Persik Kediri",
    group: 'ISL',
    data:  { hue: 351, sat: 0.85, luminance: 0.44 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 0, sat: 0, luminance: 0.12 },
  },
  {
    name:  "Persis Solo",
    group: 'ISL',
    data:  { hue: 351, sat: 0.85, luminance: 0.44 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 210, sat: 1, luminance: 0.19 },
  },
  {
    name:  "Persita Tangerang (Tangerang)",
    group: 'ISL',
    data:  { hue: 355, sat: 0.96, luminance: 0.53 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 0, sat: 0, luminance: 0.12 },
  },
  {
    name:  "PSBS Biak (Biak)",
    group: 'ISL',
    data:  { hue: 217, sat: 1, luminance: 0.27 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 48, sat: 1, luminance: 0.5 },
  },
  {
    name:  "PSIM Yogyakarta",
    group: 'ISL',
    data:  { hue: 351, sat: 0.85, luminance: 0.44 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 0, sat: 0, luminance: 0.12 },
  },
  {
    name:  "PSM Makassar",
    group: 'ISL',
    data:  { hue: 350, sat: 0.68, luminance: 0.36 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 48, sat: 1, luminance: 0.5 },
  },
  {
    name:  "Semen Padang FC (Padang)",
    group: 'ISL',
    data:  { hue: 48, sat: 1, luminance: 0.5 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  // ── Movie colorways ─────────────────────────────────────────────────────────
  {
    name:  "Psycho (1960)",
    group: 'Movies',
    data:  { hue: 0, sat: 0, luminance: 0.1 },
    map:   { hue: 350, sat: 0.85, luminance: 0.42 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  {
    name:  "2001: A Space Odyssey (1968)",
    group: 'Movies',
    data:  { hue: 0, sat: 0, luminance: 0.06 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 197, sat: 1, luminance: 0.45 },
  },
  {
    name:  "The Godfather (1972)",
    group: 'Movies',
    data:  { hue: 350, sat: 0.64, luminance: 0.33 },
    map:   { hue: 37, sat: 0.63, luminance: 0.71 },
    label: { hue: 185, sat: 0.15, luminance: 0.12 },
  },
  {
    name:  "Jaws (1975)",
    group: 'Movies',
    data:  { hue: 212, sat: 1, luminance: 0.18 },
    map:   { hue: 350, sat: 0.85, luminance: 0.42 },
    label: { hue: 41, sat: 0.98, luminance: 0.59 },
  },
  {
    name:  "Star Wars (1977)",
    group: 'Movies',
    data:  { hue: 0, sat: 0, luminance: 0.06 },
    map:   { hue: 50, sat: 1, luminance: 0.5 },
    label: { hue: 197, sat: 1, luminance: 0.45 },
  },
  {
    name:  "Alien (1979)",
    group: 'Movies',
    data:  { hue: 185, sat: 0.15, luminance: 0.12 },
    map:   { hue: 167, sat: 1, luminance: 0.5 },
    label: { hue: 350, sat: 0.85, luminance: 0.42 },
  },
  {
    name:  "The Shining (1980)",
    group: 'Movies',
    data:  { hue: 350, sat: 0.85, luminance: 0.42 },
    map:   { hue: 225, sat: 0.55, luminance: 0.23 },
    label: { hue: 41, sat: 0.69, luminance: 0.85 },
  },
  {
    name:  "Raiders of the Lost Ark (1981)",
    group: 'Movies',
    data:  { hue: 41, sat: 0.98, luminance: 0.59 },
    map:   { hue: 350, sat: 0.85, luminance: 0.42 },
    label: { hue: 212, sat: 1, luminance: 0.18 },
  },
  {
    name:  "Blade Runner (1982)",
    group: 'Movies',
    data:  { hue: 240, sat: 0.61, luminance: 0.1 },
    map:   { hue: 24, sat: 1, luminance: 0.5 },
    label: { hue: 167, sat: 1, luminance: 0.5 },
  },
  {
    name:  "The Terminator (1984)",
    group: 'Movies',
    data:  { hue: 350, sat: 0.85, luminance: 0.42 },
    map:   { hue: 0, sat: 0, luminance: 0.1 },
    label: { hue: 203, sat: 0.16, luminance: 0.8 },
  },
  {
    name:  "Back to the Future (1985)",
    group: 'Movies',
    data:  { hue: 24, sat: 1, luminance: 0.5 },
    map:   { hue: 0, sat: 0, luminance: 0.1 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  {
    name:  "Goodfellas (1990)",
    group: 'Movies',
    data:  { hue: 350, sat: 0.64, luminance: 0.33 },
    map:   { hue: 37, sat: 0.63, luminance: 0.71 },
    label: { hue: 185, sat: 0.15, luminance: 0.12 },
  },
  {
    name:  "The Silence of the Lambs (1991)",
    group: 'Movies',
    data:  { hue: 249, sat: 0.7, luminance: 0.22 },
    map:   { hue: 351, sat: 0.81, luminance: 0.49 },
    label: { hue: 203, sat: 0.16, luminance: 0.8 },
  },
  {
    name:  "Schindler's List (1993)",
    group: 'Movies',
    data:  { hue: 350, sat: 0.85, luminance: 0.42 },
    map:   { hue: 225, sat: 0.55, luminance: 0.23 },
    label: { hue: 41, sat: 0.69, luminance: 0.85 },
  },
  {
    name:  "Jurassic Park (1993)",
    group: 'Movies',
    data:  { hue: 123, sat: 0.46, luminance: 0.33 },
    map:   { hue: 50, sat: 1, luminance: 0.5 },
    label: { hue: 0, sat: 0.55, luminance: 0.39 },
  },
  {
    name:  "The Shawshank Redemption (1994)",
    group: 'Movies',
    data:  { hue: 212, sat: 0.77, luminance: 0.17 },
    map:   { hue: 48, sat: 0.89, luminance: 0.6 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  {
    name:  "Pulp Fiction (1994)",
    group: 'Movies',
    data:  { hue: 0, sat: 0, luminance: 0.12 },
    map:   { hue: 48, sat: 1, luminance: 0.5 },
    label: { hue: 350, sat: 0.85, luminance: 0.42 },
  },
  {
    name:  "The Lion King (1994)",
    group: 'Movies',
    data:  { hue: 41, sat: 0.98, luminance: 0.59 },
    map:   { hue: 143, sat: 1, luminance: 0.14 },
    label: { hue: 350, sat: 0.85, luminance: 0.42 },
  },
  {
    name:  "Toy Story (1995)",
    group: 'Movies',
    data:  { hue: 203, sat: 1, luminance: 0.38 },
    map:   { hue: 48, sat: 1, luminance: 0.5 },
    label: { hue: 0, sat: 0, luminance: 0.1 },
  },
  {
    name:  "Titanic (1997)",
    group: 'Movies',
    data:  { hue: 203, sat: 1, luminance: 0.38 },
    map:   { hue: 0, sat: 0, luminance: 0.1 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  {
    name:  "The Matrix (1999)",
    group: 'Movies',
    data:  { hue: 135, sat: 1, luminance: 0.5 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 355, sat: 1, luminance: 0.5 },
  },
  {
    name:  "Harry Potter (2001)",
    group: 'Movies',
    data:  { hue: 350, sat: 0.85, luminance: 0.42 },
    map:   { hue: 220, sat: 0.65, luminance: 0.33 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  {
    name:  "The Lord of the Rings (2003)",
    group: 'Movies',
    data:  { hue: 41, sat: 0.98, luminance: 0.59 },
    map:   { hue: 143, sat: 1, luminance: 0.14 },
    label: { hue: 0, sat: 0, luminance: 0.1 },
  },
  {
    name:  "Finding Nemo (2003)",
    group: 'Movies',
    data:  { hue: 203, sat: 1, luminance: 0.38 },
    map:   { hue: 24, sat: 1, luminance: 0.5 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  {
    name:  "Pirates of the Caribbean (2003)",
    group: 'Movies',
    data:  { hue: 0, sat: 0, luminance: 0.1 },
    map:   { hue: 41, sat: 0.98, luminance: 0.59 },
    label: { hue: 212, sat: 1, luminance: 0.18 },
  },
  {
    name:  "The Incredibles (2004)",
    group: 'Movies',
    data:  { hue: 350, sat: 0.85, luminance: 0.42 },
    map:   { hue: 220, sat: 0.65, luminance: 0.33 },
    label: { hue: 41, sat: 0.98, luminance: 0.59 },
  },
  {
    name:  "The Dark Knight (2008)",
    group: 'Movies',
    data:  { hue: 0, sat: 0, luminance: 0.1 },
    map:   { hue: 48, sat: 1, luminance: 0.44 },
    label: { hue: 260, sat: 0.52, luminance: 0.36 },
  },
  {
    name:  "Avatar (2009)",
    group: 'Movies',
    data:  { hue: 203, sat: 1, luminance: 0.38 },
    map:   { hue: 167, sat: 1, luminance: 0.5 },
    label: { hue: 350, sat: 0.85, luminance: 0.42 },
  },
  {
    name:  "Inception (2010)",
    group: 'Movies',
    data:  { hue: 212, sat: 0.77, luminance: 0.17 },
    map:   { hue: 355, sat: 0.77, luminance: 0.56 },
    label: { hue: 48, sat: 0.89, luminance: 0.6 },
  },
  {
    name:  "Interstellar (2014)",
    group: 'Movies',
    data:  { hue: 212, sat: 0.77, luminance: 0.17 },
    map:   { hue: 0, sat: 0, luminance: 0.1 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  {
    name:  "Mad Max: Fury Road (2015)",
    group: 'Movies',
    data:  { hue: 15, sat: 0.75, luminance: 0.48 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 0, sat: 0, luminance: 0.75 },
  },
  {
    name:  "Parasite (2019)",
    group: 'Movies',
    data:  { hue: 123, sat: 0.46, luminance: 0.33 },
    map:   { hue: 0, sat: 0, luminance: 0.1 },
    label: { hue: 41, sat: 0.69, luminance: 0.85 },
  },
  {
    name:  "Joker (2019)",
    group: 'Movies',
    data:  { hue: 260, sat: 0.52, luminance: 0.36 },
    map:   { hue: 48, sat: 1, luminance: 0.44 },
    label: { hue: 0, sat: 0, luminance: 0.1 },
  },
  {
    name:  "Avengers: Endgame (2019)",
    group: 'Movies',
    data:  { hue: 350, sat: 0.85, luminance: 0.42 },
    map:   { hue: 220, sat: 0.65, luminance: 0.33 },
    label: { hue: 40, sat: 0.98, luminance: 0.57 },
  },
  {
    name:  "Dune (2021)",
    group: 'Movies',
    data:  { hue: 15, sat: 0.75, luminance: 0.48 },
    map:   { hue: 213, sat: 0.68, luminance: 0.15 },
    label: { hue: 41, sat: 0.98, luminance: 0.59 },
  },
  {
    name:  "Spider-Man: No Way Home (2021)",
    group: 'Movies',
    data:  { hue: 350, sat: 0.85, luminance: 0.42 },
    map:   { hue: 220, sat: 0.65, luminance: 0.33 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  {
    name:  "Everything Everywhere All at Once (2022)",
    group: 'Movies',
    data:  { hue: 24, sat: 1, luminance: 0.5 },
    map:   { hue: 167, sat: 1, luminance: 0.5 },
    label: { hue: 249, sat: 0.7, luminance: 0.22 },
  },
  {
    name:  "Barbie (2023)",
    group: 'Movies',
    data:  { hue: 330, sat: 1, luminance: 0.65 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 197, sat: 1, luminance: 0.5 },
  },
  {
    name:  "Oppenheimer (2023)",
    group: 'Movies',
    data:  { hue: 350, sat: 0.85, luminance: 0.42 },
    map:   { hue: 0, sat: 0, luminance: 0.1 },
    label: { hue: 40, sat: 0.98, luminance: 0.57 },
  },
  {
    name:  "Dune: Part Two (2024)",
    group: 'Movies',
    data:  { hue: 15, sat: 0.75, luminance: 0.48 },
    map:   { hue: 213, sat: 0.68, luminance: 0.15 },
    label: { hue: 41, sat: 0.98, luminance: 0.59 },
  },

  // ── Star Wars colorways ─────────────────────────────────────────────────────
  {
    name:  "Clone Troopers (Kamino)",
    group: 'StarWars',
    data:  { hue: 0, sat: 0, luminance: 0.94 },
    map:   { hue: 212, sat: 0.65, luminance: 0.34 },
    label: { hue: 350, sat: 0.85, luminance: 0.42 },
  },
  {
    name:  "Jedi Order (Coruscant)",
    group: 'StarWars',
    data:  { hue: 203, sat: 1, luminance: 0.38 },
    map:   { hue: 30, sat: 0.35, luminance: 0.55 },
    label: { hue: 140, sat: 1, luminance: 0.4 },
  },
  {
    name:  "Mandalorians (Mandalore)",
    group: 'StarWars',
    data:  { hue: 210, sat: 0.15, luminance: 0.75 },
    map:   { hue: 215, sat: 0.8, luminance: 0.22 },
    label: { hue: 44, sat: 0.92, luminance: 0.6 },
  },
  {
    name:  "Rebel Alliance (Yavin 4)",
    group: 'StarWars',
    data:  { hue: 345, sat: 0.85, luminance: 0.44 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 212, sat: 1, luminance: 0.18 },
  },
  {
    name:  "Resistance (D'Qar)",
    group: 'StarWars',
    data:  { hue: 27, sat: 0.91, luminance: 0.55 },
    map:   { hue: 205, sat: 1, luminance: 0.36 },
    label: { hue: 0, sat: 0, luminance: 0.12 },
  },
  {
    name:  "First Order (Starkiller Base)",
    group: 'StarWars',
    data:  { hue: 350, sat: 0.85, luminance: 0.42 },
    map:   { hue: 215, sat: 0.4, luminance: 0.12 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  {
    name:  "Galactic Empire (Coruscant)",
    group: 'StarWars',
    data:  { hue: 240, sat: 0.1, luminance: 0.08 },
    map:   { hue: 350, sat: 0.85, luminance: 0.42 },
    label: { hue: 0, sat: 0, luminance: 0.66 },
  },
  {
    name:  "Knights of Ren (Unknown Regions)",
    group: 'StarWars',
    data:  { hue: 240, sat: 0.25, luminance: 0.15 },
    map:   { hue: 350, sat: 0.75, luminance: 0.42 },
    label: { hue: 260, sat: 0.45, luminance: 0.4 },
  },
  {
    name:  "Separatist Alliance (Geonosis)",
    group: 'StarWars',
    data:  { hue: 195, sat: 1, luminance: 0.45 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 42, sat: 0.75, luminance: 0.55 },
  },
  {
    name:  "Sith Order (Exegol)",
    group: 'StarWars',
    data:  { hue: 348, sat: 0.8, luminance: 0.34 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 45, sat: 1, luminance: 0.6 },
  },
  {
    name:  "Black Sun Syndicate (Coruscant)",
    group: 'StarWars',
    data:  { hue: 348, sat: 0.8, luminance: 0.34 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 44, sat: 0.92, luminance: 0.6 },
  },
  {
    name:  "Bounty Hunters Guild (Various)",
    group: 'StarWars',
    data:  { hue: 0, sat: 0, luminance: 0.29 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 203, sat: 0.16, luminance: 0.8 },
  },
  {
    name:  "Hutt Cartel (Nal Hutta)",
    group: 'StarWars',
    data:  { hue: 120, sat: 0.61, luminance: 0.34 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 41, sat: 0.98, luminance: 0.59 },
  },
  {
    name:  "Pirate Coalition (Florrum)",
    group: 'StarWars',
    data:  { hue: 24, sat: 1, luminance: 0.47 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 210, sat: 0.15, luminance: 0.75 },
  },
  {
    name:  "Smugglers Alliance (Corellia)",
    group: 'StarWars',
    data:  { hue: 44, sat: 0.92, luminance: 0.6 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 195, sat: 1, luminance: 0.45 },
  },
  {
    name:  "Ahsoka Tano (Shili)",
    group: 'StarWars',
    data:  { hue: 24, sat: 1, luminance: 0.53 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  {
    name:  "BB-8 (D'Qar)",
    group: 'StarWars',
    data:  { hue: 27, sat: 0.91, luminance: 0.55 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 205, sat: 1, luminance: 0.36 },
  },
  {
    name:  "C-3PO (Tatooine)",
    group: 'StarWars',
    data:  { hue: 44, sat: 0.92, luminance: 0.6 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 0, sat: 0, luminance: 0.94 },
  },
  {
    name:  "Chewbacca (Kashyyyk)",
    group: 'StarWars',
    data:  { hue: 25, sat: 0.7, luminance: 0.35 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 210, sat: 0.15, luminance: 0.75 },
  },
  {
    name:  "Finn (Unknown)",
    group: 'StarWars',
    data:  { hue: 27, sat: 0.91, luminance: 0.55 },
    map:   { hue: 205, sat: 1, luminance: 0.36 },
    label: { hue: 0, sat: 0, luminance: 0.12 },
  },
  {
    name:  "Han Solo (Corellia)",
    group: 'StarWars',
    data:  { hue: 44, sat: 0.92, luminance: 0.6 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  {
    name:  "K-2SO (Jedha)",
    group: 'StarWars',
    data:  { hue: 210, sat: 0.15, luminance: 0.75 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 350, sat: 0.85, luminance: 0.42 },
  },
  {
    name:  "Lando Calrissian (Socorro)",
    group: 'StarWars',
    data:  { hue: 44, sat: 0.92, luminance: 0.6 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 345, sat: 0.85, luminance: 0.44 },
  },
  {
    name:  "Luke Skywalker (Tatooine)",
    group: 'StarWars',
    data:  { hue: 140, sat: 1, luminance: 0.4 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 203, sat: 1, luminance: 0.38 },
  },
  {
    name:  "Mace Windu (Haruun Kal)",
    group: 'StarWars',
    data:  { hue: 271, sat: 1, luminance: 0.26 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 0, sat: 0, luminance: 0.94 },
  },
  {
    name:  "Obi-Wan Kenobi (Stewjon)",
    group: 'StarWars',
    data:  { hue: 203, sat: 1, luminance: 0.38 },
    map:   { hue: 36, sat: 0.45, luminance: 0.8 },
    label: { hue: 27, sat: 0.55, luminance: 0.35 },
  },
  {
    name:  "Princess Leia (Alderaan)",
    group: 'StarWars',
    data:  { hue: 0, sat: 0, luminance: 1 },
    map:   { hue: 44, sat: 0.92, luminance: 0.6 },
    label: { hue: 345, sat: 0.85, luminance: 0.44 },
  },
  {
    name:  "Qui-Gon Jinn (Coruscant)",
    group: 'StarWars',
    data:  { hue: 120, sat: 0.61, luminance: 0.34 },
    map:   { hue: 25, sat: 0.7, luminance: 0.35 },
    label: { hue: 44, sat: 0.92, luminance: 0.6 },
  },
  {
    name:  "R2-D2 (Naboo)",
    group: 'StarWars',
    data:  { hue: 195, sat: 1, luminance: 0.45 },
    map:   { hue: 0, sat: 0, luminance: 1 },
    label: { hue: 0, sat: 0, luminance: 0.12 },
  },
  {
    name:  "Rey Skywalker (Jakku)",
    group: 'StarWars',
    data:  { hue: 44, sat: 0.92, luminance: 0.6 },
    map:   { hue: 36, sat: 0.4, luminance: 0.75 },
    label: { hue: 210, sat: 0.15, luminance: 0.75 },
  },
  {
    name:  "Yoda (Dagobah)",
    group: 'StarWars',
    data:  { hue: 150, sat: 1, luminance: 0.3 },
    map:   { hue: 25, sat: 0.35, luminance: 0.55 },
    label: { hue: 0, sat: 0, luminance: 0.94 },
  },
  {
    name:  "Boba Fett (Kamino)",
    group: 'StarWars',
    data:  { hue: 122, sat: 0.7, luminance: 0.45 },
    map:   { hue: 345, sat: 0.85, luminance: 0.44 },
    label: { hue: 203, sat: 0.16, luminance: 0.8 },
  },
  {
    name:  "Captain Phasma (Parnassos)",
    group: 'StarWars',
    data:  { hue: 203, sat: 0.16, luminance: 0.8 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 350, sat: 0.85, luminance: 0.42 },
  },
  {
    name:  "Count Dooku (Serenno)",
    group: 'StarWars',
    data:  { hue: 212, sat: 1, luminance: 0.18 },
    map:   { hue: 350, sat: 0.85, luminance: 0.42 },
    label: { hue: 44, sat: 0.92, luminance: 0.6 },
  },
  {
    name:  "Darth Bane (Moraband)",
    group: 'StarWars',
    data:  { hue: 0, sat: 0, luminance: 0.12 },
    map:   { hue: 350, sat: 0.85, luminance: 0.42 },
    label: { hue: 260, sat: 0.45, luminance: 0.4 },
  },
  {
    name:  "Darth Maul (Dathomir)",
    group: 'StarWars',
    data:  { hue: 350, sat: 0.85, luminance: 0.42 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 44, sat: 0.92, luminance: 0.6 },
  },
  {
    name:  "Darth Revan (Unknown)",
    group: 'StarWars',
    data:  { hue: 260, sat: 0.45, luminance: 0.4 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 350, sat: 0.85, luminance: 0.42 },
  },
  {
    name:  "Darth Sidious (Naboo)",
    group: 'StarWars',
    data:  { hue: 348, sat: 0.8, luminance: 0.34 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 45, sat: 1, luminance: 0.6 },
  },
  {
    name:  "Darth Tyranus (Serenno)",
    group: 'StarWars',
    data:  { hue: 212, sat: 1, luminance: 0.18 },
    map:   { hue: 350, sat: 0.85, luminance: 0.42 },
    label: { hue: 44, sat: 0.92, luminance: 0.6 },
  },
  {
    name:  "Darth Vader (Mustafar)",
    group: 'StarWars',
    data:  { hue: 0, sat: 0, luminance: 0.12 },
    map:   { hue: 350, sat: 0.85, luminance: 0.42 },
    label: { hue: 0, sat: 0, luminance: 0.66 },
  },
  {
    name:  "Emperor Palpatine (Naboo)",
    group: 'StarWars',
    data:  { hue: 348, sat: 0.8, luminance: 0.34 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 45, sat: 1, luminance: 0.6 },
  },
  {
    name:  "General Grievous (Kalee)",
    group: 'StarWars',
    data:  { hue: 0, sat: 0, luminance: 0.66 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 350, sat: 0.85, luminance: 0.42 },
  },
  {
    name:  "General Hux (Arkanis)",
    group: 'StarWars',
    data:  { hue: 350, sat: 0.85, luminance: 0.42 },
    map:   { hue: 215, sat: 0.4, luminance: 0.12 },
    label: { hue: 0, sat: 0, luminance: 1 },
  },
  {
    name:  "Kylo Ren (Chandrila)",
    group: 'StarWars',
    data:  { hue: 240, sat: 0.25, luminance: 0.15 },
    map:   { hue: 350, sat: 0.75, luminance: 0.42 },
    label: { hue: 0, sat: 0, luminance: 0.42 },
  },
  {
    name:  "Supreme Leader Snoke (Unknown Regions)",
    group: 'StarWars',
    data:  { hue: 240, sat: 0.25, luminance: 0.15 },
    map:   { hue: 0, sat: 0, luminance: 0.66 },
    label: { hue: 350, sat: 0.75, luminance: 0.42 },
  },
  {
    name:  "Cad Bane (Duro)",
    group: 'StarWars',
    data:  { hue: 0, sat: 0, luminance: 0.12 },
    map:   { hue: 345, sat: 0.85, luminance: 0.44 },
    label: { hue: 44, sat: 0.92, luminance: 0.6 },
  },
  {
    name:  "Din Djarin (Mandalore)",
    group: 'StarWars',
    data:  { hue: 210, sat: 0.15, luminance: 0.75 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 44, sat: 0.92, luminance: 0.6 },
  },
  {
    name:  "Fennec Shand (Tatooine)",
    group: 'StarWars',
    data:  { hue: 0, sat: 0, luminance: 0.12 },
    map:   { hue: 345, sat: 0.85, luminance: 0.44 },
    label: { hue: 210, sat: 0.15, luminance: 0.75 },
  },
  {
    name:  "Hondo Ohnaka (Florrum)",
    group: 'StarWars',
    data:  { hue: 24, sat: 1, luminance: 0.47 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 210, sat: 0.15, luminance: 0.75 },
  },
  {
    name:  "IG-11 (Unknown)",
    group: 'StarWars',
    data:  { hue: 210, sat: 0.15, luminance: 0.75 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 350, sat: 0.85, luminance: 0.42 },
  },
  {
    name:  "Jango Fett (Concord Dawn)",
    group: 'StarWars',
    data:  { hue: 122, sat: 0.7, luminance: 0.45 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 203, sat: 0.16, luminance: 0.8 },
  },
  {
    name:  "L3-37 (Kessel)",
    group: 'StarWars',
    data:  { hue: 203, sat: 0.16, luminance: 0.8 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 195, sat: 1, luminance: 0.45 },
  },
  {
    name:  "Qi'ra (Corellia)",
    group: 'StarWars',
    data:  { hue: 348, sat: 0.8, luminance: 0.34 },
    map:   { hue: 0, sat: 0, luminance: 0.12 },
    label: { hue: 44, sat: 0.92, luminance: 0.6 },
  },
  // ── Cyberpunk colorways ─────────────────────────────────────────────────────
  {
    name:  "Neon Nights",
    group: 'Cyberpunk',
    data:  { hue: 324, sat: 1, luminance: 0.5 },
    map:   { hue: 182, sat: 1, luminance: 0.5 },
    label: { hue: 240, sat: 0.51, luminance: 0.08 },
  },
  {
    name:  "Violet Haze",
    group: 'Cyberpunk',
    data:  { hue: 284, sat: 1, luminance: 0.5 },
    map:   { hue: 330, sat: 1, luminance: 0.55 },
    label: { hue: 265, sat: 0.64, luminance: 0.12 },
  },
  {
    name:  "Acid Protocol",
    group: 'Cyberpunk',
    data:  { hue: 157, sat: 1, luminance: 0.5 },
    map:   { hue: 188, sat: 1, luminance: 0.5 },
    label: { hue: 192, sat: 0.64, luminance: 0.08 },
  },
  {
    name:  "Blood Chrome",
    group: 'Cyberpunk',
    data:  { hue: 345, sat: 1, luminance: 0.5 },
    map:   { hue: 180, sat: 1, luminance: 0.5 },
    label: { hue: 330, sat: 0.44, luminance: 0.07 },
  },
  {
    name:  "Glitch Magenta",
    group: 'Cyberpunk',
    data:  { hue: 293, sat: 1, luminance: 0.5 },
    map:   { hue: 110, sat: 1, luminance: 0.53 },
    label: { hue: 266, sat: 0.58, luminance: 0.07 },
  },
  {
    name:  "Electric Blue Drift",
    group: 'Cyberpunk',
    data:  { hue: 204, sat: 1, luminance: 0.5 },
    map:   { hue: 55, sat: 1, luminance: 0.5 },
    label: { hue: 229, sat: 0.43, luminance: 0.1 },
  },
  {
    name:  "Pink Synthwave",
    group: 'Cyberpunk',
    data:  { hue: 341, sat: 1, luminance: 0.58 },
    map:   { hue: 175, sat: 0.95, luminance: 0.46 },
    label: { hue: 270, sat: 0.5, luminance: 0.11 },
  },
  {
    name:  "Shadow Grid",
    group: 'Cyberpunk',
    data:  { hue: 167, sat: 1, luminance: 0.5 },
    map:   { hue: 320, sat: 1, luminance: 0.5 },
    label: { hue: 240, sat: 0.26, luminance: 0.08 },
  },
  {
    name:  "Chrome Rain",
    group: 'Cyberpunk',
    data:  { hue: 199, sat: 1, luminance: 0.7 },
    map:   { hue: 36, sat: 1, luminance: 0.5 },
    label: { hue: 240, sat: 0.33, luminance: 0.1 },
  },
  {
    name:  "Digital Void",
    group: 'Cyberpunk',
    data:  { hue: 276, sat: 1, luminance: 0.5 },
    map:   { hue: 144, sat: 1, luminance: 0.5 },
    label: { hue: 240, sat: 0.5, luminance: 0.03 },
  },
  {
    name:  "Neon Overload",
    group: 'Cyberpunk',
    data:  { hue: 300, sat: 1, luminance: 0.5 },
    map:   { hue: 180, sat: 1, luminance: 0.5 },
    label: { hue: 300, sat: 1, luminance: 0.05 },
  },
  {
    name:  "Cyber Sunset",
    group: 'Cyberpunk',
    data:  { hue: 24, sat: 1, luminance: 0.5 },
    map:   { hue: 72, sat: 1, luminance: 0.5 },
    label: { hue: 326, sat: 0.49, luminance: 0.11 },
  },
  {
    name:  "Holo Grid",
    group: 'Cyberpunk',
    data:  { hue: 199, sat: 1, luminance: 0.5 },
    map:   { hue: 300, sat: 1, luminance: 0.5 },
    label: { hue: 205, sat: 0.64, luminance: 0.1 },
  },
  {
    name:  "Pulse Red",
    group: 'Cyberpunk',
    data:  { hue: 11, sat: 1, luminance: 0.5 },
    map:   { hue: 167, sat: 1, luminance: 0.5 },
    label: { hue: 0, sat: 0.51, luminance: 0.08 },
  },
  {
    name:  "Matrix Echo",
    group: 'Cyberpunk',
    data:  { hue: 120, sat: 1, luminance: 0.6 },
    map:   { hue: 300, sat: 1, luminance: 0.5 },
    label: { hue: 120, sat: 0.26, luminance: 0.08 },
  },
  // ── Retro colorways ─────────────────────────────────────────────────────────
  {
    name:  "Diner Chrome",
    group: 'Retro',
    data:  { hue: 0, sat: 0.86, luminance: 0.55 },
    map:   { hue: 185, sat: 1, luminance: 0.39 },
    label: { hue: 45, sat: 1, luminance: 0.6 },
  },
  {
    name:  "Flower Power",
    group: 'Retro',
    data:  { hue: 334, sat: 1, luminance: 0.5 },
    map:   { hue: 75, sat: 1, luminance: 0.5 },
    label: { hue: 25, sat: 1, luminance: 0.5 },
  },
  {
    name:  "Harvest Earth",
    group: 'Retro',
    data:  { hue: 18, sat: 0.67, luminance: 0.55 },
    map:   { hue: 86, sat: 0.32, luminance: 0.46 },
    label: { hue: 40, sat: 0.7, luminance: 0.59 },
  },
  {
    name:  "Studio 54",
    group: 'Retro',
    data:  { hue: 340, sat: 0.82, luminance: 0.52 },
    map:   { hue: 291, sat: 0.64, luminance: 0.42 },
    label: { hue: 45, sat: 1, luminance: 0.51 },
  },
  {
    name:  "Vice Glow",
    group: 'Retro',
    data:  { hue: 324, sat: 1, luminance: 0.5 },
    map:   { hue: 182, sat: 1, luminance: 0.5 },
    label: { hue: 64, sat: 1, luminance: 0.5 },
  },
  {
    name:  "Outrun Nights",
    group: 'Retro',
    data:  { hue: 341, sat: 1, luminance: 0.58 },
    map:   { hue: 184, sat: 0.96, luminance: 0.46 },
    label: { hue: 269, sat: 1, luminance: 0.56 },
  },
  {
    name:  "Vapor Dream",
    group: 'Retro',
    data:  { hue: 321, sat: 1, luminance: 0.72 },
    map:   { hue: 192, sat: 0.99, luminance: 0.5 },
    label: { hue: 272, sat: 1, luminance: 0.7 },
  },
  {
    name:  "Memphis Pop",
    group: 'Retro',
    data:  { hue: 0, sat: 1, luminance: 0.65 },
    map:   { hue: 189, sat: 1, luminance: 0.65 },
    label: { hue: 53, sat: 1, luminance: 0.65 },
  },
  {
    name:  "Flannel Grunge",
    group: 'Retro',
    data:  { hue: 0, sat: 0, luminance: 0.17 },
    map:   { hue: 29, sat: 0.53, luminance: 0.36 },
    label: { hue: 0, sat: 1, luminance: 0.65 },
  },
  {
    name:  "Pixel Quest",
    group: 'Retro',
    data:  { hue: 120, sat: 1, luminance: 0.5 },
    map:   { hue: 300, sat: 1, luminance: 0.5 },
    label: { hue: 60, sat: 1, luminance: 0.5 },
  },
  {
    name:  "Millennium Holo",
    group: 'Retro',
    data:  { hue: 312, sat: 1, luminance: 0.5 },
    map:   { hue: 168, sat: 1, luminance: 0.5 },
    label: { hue: 72, sat: 1, luminance: 0.5 },
  },
  {
    name:  "Mod Pop",
    group: 'Retro',
    data:  { hue: 349, sat: 1, luminance: 0.59 },
    map:   { hue: 217, sat: 1, luminance: 0.59 },
    label: { hue: 48, sat: 1, luminance: 0.5 },
  },
  {
    name:  "Atomic Era",
    group: 'Retro',
    data:  { hue: 13, sat: 0.68, luminance: 0.63 },
    map:   { hue: 233, sat: 0.18, luminance: 0.29 },
    label: { hue: 151, sat: 0.24, luminance: 0.6 },
  },
  {
    name:  "Neon Blade",
    group: 'Retro',
    data:  { hue: 157, sat: 1, luminance: 0.5 },
    map:   { hue: 320, sat: 1, luminance: 0.5 },
    label: { hue: 188, sat: 1, luminance: 0.5 },
  },
  {
    name:  "Sunset Boho",
    group: 'Retro',
    data:  { hue: 12, sat: 0.76, luminance: 0.61 },
    map:   { hue: 111, sat: 0.25, luminance: 0.35 },
    label: { hue: 27, sat: 0.87, luminance: 0.67 },
  },

].sort((a, b) => {
  const ORDER = ['Mono', 'Running', 'Kopi', 'Sneakers', 'Luxury', 'Brand', 'EPL', 'ISL', 'NBA', 'Movies', 'Comics', 'StarWars', 'TMNT', 'Retro', 'Cyberpunk', 'MechKeeb', 'IDE'];
  const ai = ORDER.indexOf(a.group);
  const bi = ORDER.indexOf(b.group);
  if (ai !== bi) return ai - bi;
  if (a.group === 'Running') return a.name.localeCompare(b.name);
  return 0;
});